//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHotel220.Clients.Core {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartHotel220.Clients.Core.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активировать ЭКО-режим.
        /// </summary>
        internal static string ActivateEcoMode {
            get {
                return ResourceManager.GetString("ActivateEcoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мероприятия.
        /// </summary>
        internal static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окружающий свет.
        /// </summary>
        internal static string AmbientLight {
            get {
                return ResourceManager.GetString("AmbientLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки окружения.
        /// </summary>
        internal static string AmbientSettings {
            get {
                return ResourceManager.GetString("AmbientSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to График уборки.
        /// </summary>
        internal static string BeGreen {
            get {
                return ResourceManager.GetString("BeGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАБРОНИРОВАТЬ КОНФЕРЕНЦ-ЗАЛ.
        /// </summary>
        internal static string BookConferenceMayus {
            get {
                return ResourceManager.GetString("BookConferenceMayus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАБРОНИРОВАТЬ НОМЕР.
        /// </summary>
        internal static string BookMayus {
            get {
                return ResourceManager.GetString("BookMayus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось запустить бота..
        /// </summary>
        internal static string BotError {
            get {
                return ResourceManager.GetString("BotError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите приложение для обмена сообщениями..
        /// </summary>
        internal static string BotSelectionMessage {
            get {
                return ResourceManager.GetString("BotSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор бота.
        /// </summary>
        internal static string BotSelectionTitle {
            get {
                return ResourceManager.GetString("BotSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация/выписка.
        /// </summary>
        internal static string CheckInOut {
            get {
                return ResourceManager.GetString("CheckInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выписаться.
        /// </summary>
        internal static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скоро.
        /// </summary>
        internal static string Coming {
            get {
                return ResourceManager.GetString("Coming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конференц-зал.
        /// </summary>
        internal static string ConferenceRoom {
            get {
                return ResourceManager.GetString("ConferenceRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У Вас нет учётной записи?.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий URL-адрес файла JSON:.
        /// </summary>
        internal static string CurrentJson {
            get {
                return ResourceManager.GetString("CurrentJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деактивировать ЭКО-режим.
        /// </summary>
        internal static string DeactivateEcoMode {
            get {
                return ResourceManager.GetString("DeactivateEcoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите забронировать номер в &quot;{0}&quot;?.
        /// </summary>
        internal static string DialogBookingMessage {
            get {
                return ResourceManager.GetString("DialogBookingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование.
        /// </summary>
        internal static string DialogBookingTitle {
            get {
                return ResourceManager.GetString("DialogBookingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string DialogNo {
            get {
                return ResourceManager.GetString("DialogNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        internal static string DialogOk {
            get {
                return ResourceManager.GetString("DialogOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string DialogYes {
            get {
                return ResourceManager.GetString("DialogYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что Вы хотите сделать сегодня?.
        /// </summary>
        internal static string DoToday {
            get {
                return ResourceManager.GetString("DoToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двухместный номер.
        /// </summary>
        internal static string DoubleRoom {
            get {
                return ResourceManager.GetString("DoubleRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что Вы хотите сегодня есть?.
        /// </summary>
        internal static string EatToday {
            get {
                return ResourceManager.GetString("EatToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только пользователи B2C могут забронировать номер..
        /// </summary>
        internal static string ExceptionB2CMessage {
            get {
                return ResourceManager.GetString("ExceptionB2CMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка, повторите попытку.
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string ExceptionTitle {
            get {
                return ResourceManager.GetString("ExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти мой номер.
        /// </summary>
        internal static string FindRoom {
            get {
                return ResourceManager.GetString("FindRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В МОЙ НОМЕР.
        /// </summary>
        internal static string GoMyRoomMayus {
            get {
                return ResourceManager.GetString("GoMyRoomMayus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравствуйте,.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Занятость в выбранные числа очень высока. Скорее забронируйте свой номер!.
        /// </summary>
        internal static string HighOccupancy {
            get {
                return ResourceManager.GetString("HighOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка связи: {0}.
        /// </summary>
        internal static string HttpRequestExceptionMessage {
            get {
                return ResourceManager.GetString("HttpRequestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string HttpRequestExceptionTitle {
            get {
                return ResourceManager.GetString("HttpRequestExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индивидуальный номер.
        /// </summary>
        internal static string IndividualRoom {
            get {
                return ResourceManager.GetString("IndividualRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка с JSON.
        /// </summary>
        internal static string LoadJson {
            get {
                return ResourceManager.GetString("LoadJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высокая доступность в выбранные даты..
        /// </summary>
        internal static string LowOccupancy {
            get {
                return ResourceManager.GetString("LowOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Занятость в выбранные числа значительная..
        /// </summary>
        internal static string MediumOccupancy {
            get {
                return ResourceManager.GetString("MediumOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Громкость музыки.
        /// </summary>
        internal static string MusicVolume {
            get {
                return ResourceManager.GetString("MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СДЕЛАТЬ НОВОЕ БРОНИРОВАНИЕ.
        /// </summary>
        internal static string NewBookingMayus {
            get {
                return ResourceManager.GetString("NewBookingMayus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДАЛЬШЕ.
        /// </summary>
        internal static string NextMayus {
            get {
                return ResourceManager.GetString("NextMayus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, проведите своё устройство.
        /// </summary>
        internal static string NfcMessage01 {
            get {
                return ResourceManager.GetString("NfcMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в области карты NFC..
        /// </summary>
        internal static string NfcMessage02 {
            get {
                return ResourceManager.GetString("NfcMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC недоступен.
        /// </summary>
        internal static string NoNfc {
            get {
                return ResourceManager.GetString("NoNfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет уведомлений.
        /// </summary>
        internal static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не реализовано.
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть двери.
        /// </summary>
        internal static string OpenDoor {
            get {
                return ResourceManager.GetString("OpenDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалённый URL-адрес файла JSON.
        /// </summary>
        internal static string RemoteJson {
            get {
                return ResourceManager.GetString("RemoteJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресторан.
        /// </summary>
        internal static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзывы.
        /// </summary>
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номера.
        /// </summary>
        internal static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура в номере.
        /// </summary>
        internal static string RoomTemperature {
            get {
                return ResourceManager.GetString("RoomTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все +.
        /// </summary>
        internal static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надеемся увидеть Вас снова.
        /// </summary>
        internal static string SeeYou {
            get {
                return ResourceManager.GetString("SeeYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обслуживание.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВОЙТИ.
        /// </summary>
        internal static string SignInMayus {
            get {
                return ResourceManager.GetString("SignInMayus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВОЙТИ ЧЕРЕЗ AAD B2C.
        /// </summary>
        internal static string SignInMicrosoftMayus {
            get {
                return ResourceManager.GetString("SignInMicrosoftMayus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предложения.
        /// </summary>
        internal static string Suggestions {
            get {
                return ResourceManager.GetString("Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отель.
        /// </summary>
        internal static string TheHotel {
            get {
                return ResourceManager.GetString("TheHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Где.
        /// </summary>
        internal static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жалюзи.
        /// </summary>
        internal static string WindowBlinds {
            get {
                return ResourceManager.GetString("WindowBlinds", resourceCulture);
            }
        }
    }
}
